### PR TITLE
[5.x] Adds option available in 5.x to use v6 API format

### PR DESCRIPTION
**Pull request by tylersmalley**
This was added in https://github.com/elastic/kibana/pull/10481

### CODE REVIEW

**Comment by jarpy** [comment]
Thanks so much for keeping this in sync with Kibana proper. Does this apply to all 5.x versions?

**Comment by tylersmalley** [comment]
No problem - trying to come up with a better way to manage this or capture a full list of options but I will update for now.

This option is being added to Kibana in 5.4.

**Comment by jarpy** [comment]
Merged this manually. Thanks again!

**Comment by jarpy** [comment]
https://github.com/elastic/kibana-docker/commit/dc6f87f910a6bb6c9ce37ad6d68653c83b4825d2

**Pull request closed without merging**
