### PR TITLE
Overrides cgroup path

### PR DESCRIPTION
**Pull request by tylersmalley**
Similar to https://github.com/elastic/elasticsearch-docker/pull/25 we need to override the cgroup cpu and cpuacct paths.

### CODE REVIEW

**Comment by tylersmalley** [comment]
Blocked on https://github.com/elastic/kibana/pull/10402

**Comment by tylersmalley** [comment]
elastic/kibana#10402 has been merged so this is ready for review. A PR specific to 5.x will soon follow.

**Comment by jarpy** [comment]
Thanks @tylersmalley. Which versions will this apply to? Is it for all 5.x versions?

**Comment by tylersmalley** [comment]
This should target 5.4, 5.x and 6.0 (master)

**Pull request merged**
