### PR TITLE
Allow extra arguments to be passed to kibana

### PR DESCRIPTION
**Pull request by giannello**
The whitelist of allowed kibana settings ignores third-party plugins configuration entries.
By passing all the args to kibana directly, it would be possible to configure plugins via ARGS, without having to rebuild the image.

### CODE REVIEW

**Comment by Shifter2600** [comment]
Wouldn't mapping the kibana.yml in a volume outside the container work for this.

**Comment by giannello** [comment]
It could work, however we would like to store credentials in configuration files, and rather pass them as environment variables.

**Comment by jarpy** [comment]
This is useful for all sorts of things. We do this for other products, and I'm frankly surprised that nobody (including me) has noticed it missing from kibana-docker before.

Thank you, @giannello!

**Comment by jarpy** [comment]
I just pushed an image with this patch, in case you'd like run it now.

```
docker.elastic.co/kibana/kibana:5.6.4-1fdad85
```

**Pull request merged**
